Condense commands

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,10 +18,10 @@ before_script:
     docker info
     docker version
 
-    # Terminate the build on errors
-  - set -e
-
   - |
+    # Terminate the build on errors
+    set -e
+
     # Process variables
     PIPELINE="${TRAVIS_BRANCH}"
     if [ "${APPID}" = 90 ]; then
